CREATE TABLE "jobs" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"title" varchar(255) NOT NULL,
	"company" varchar(255) NOT NULL,
	"company_website" varchar(500),
	"company_size" varchar(50),
	"industry" varchar(100),
	"job_level" varchar(50),
	"employment_type" varchar(50) NOT NULL,
	"department" varchar(100),
	"work_arrangement" varchar(50) NOT NULL,
	"timezone" varchar(100),
	"country" varchar(100),
	"city" varchar(100),
	"specific_location" varchar(255),
	"relocation_assistance" boolean DEFAULT false,
	"salary_min" integer,
	"salary_max" integer,
	"currency" varchar(10) DEFAULT 'USD',
	"salary_type" varchar(50),
	"equity_offered" boolean DEFAULT false,
	"bonus_structure" varchar(255),
	"years_experience" varchar(50),
	"education_level" varchar(100),
	"required_certifications" text,
	"preferred_certifications" text,
	"required_skills" text,
	"preferred_skills" text,
	"wcag_level" varchar(50),
	"accessibility_focus" text,
	"assistive_tech_experience" text,
	"description" text NOT NULL,
	"key_responsibilities" text NOT NULL,
	"requirements" text NOT NULL,
	"nice_to_have" text,
	"benefits" text,
	"professional_development" boolean DEFAULT false,
	"health_insurance" boolean DEFAULT false,
	"retirement" boolean DEFAULT false,
	"pto_details" varchar(255),
	"contact_email" varchar(255) NOT NULL,
	"application_deadline" timestamp,
	"expected_start_date" varchar(100),
	"visa_sponsorship" boolean DEFAULT false,
	"security_clearance" boolean DEFAULT false,
	"travel_required" varchar(50),
	"additional_notes" text,
	"location" varchar(255),
	"type" varchar(50),
	"salary_range" varchar(100),
	"job_source" varchar(50),
	"source_url" varchar(500),
	"status" varchar(20) DEFAULT 'pending' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
